Us24backend
SilviaPabon/AUTO-UPB pull request #115
Opened 2022-03-04 08:56 UTC by SilviaPabon

# US_24 Completada y US_37

## DESCRIPCIÓN

Descripción de la característica que se implementó.

## CAPTURAS DE PANTALLA

![image](https://user-images.githubusercontent.com/62608580/156731271-54c6b43d-e73e-4117-85ff-2a79ba4430ac.png)

us37
![image](https://user-images.githubusercontent.com/62608580/156731369-41722942-856f-492d-b124-6dc08f587e77.png)

![image](https://user-images.githubusercontent.com/62608580/156731468-92bd0746-2de2-4404-b977-cf16e5a98123.png)

## ENLACE DEL VÍDEO

## ELIMINACIÓN O CONSERVACIÓN DE LA RAMA

A la última persona en hacer la revisión, por tanto, la encargada de hacer el merge, se le solicita: 

- [x] Eliminar la rama al hacer el merge
- [ ] Conservar la rama al hacer el merge

## COMENTARIOS ADICIONALES

Ver los commits y archivos

2022-03-04 10:56 UTC, danielcadena02 approved these changes

2022-03-04 13:34 UTC, diegoaach submitted a review, later dismissed

2022-03-04 16:57 UTC, PedroChaparro requested changes
Modificar las imágenes de los accesorios al tamaño 1280 x 720, por cuestiones de estandarización y reducir peso de la imagen. 

Puede usar estas, si desea, ya están redimensionadas: 
https://i.ibb.co/YPftvWc/Tapete-rojo-para-carro.jpg
https://i.ibb.co/pnz6Y9k/Tapete-negro-para-carro.jpg

2022-03-04 17:37 UTC, PedroChaparro reviewed
@SilviaPabon ya está identificado el problema de la nav. Lo arreglamos en 5 segundos cuando quiera.

2022-03-04 17:37 UTC, PedroChaparro commented on src/controllers/admin_controller.js
> +    req.flash('success', 'SUCCESS: was updated successfully');
Recordar que la página la estamos manejando en español.

2022-03-05 00:23 UTC, PedroChaparro approved these changes

2022-03-05 02:48 UTC, diegoaach approved these changes

2022-03-05 21:49 UTC, danielcadena02 approved these changes

2022-03-05 21:49 UTC, merged