US-12
SilviaPabon/AUTO-UPB pull request #144
Opened 2022-03-19 23:13 UTC by danielcadena02

# TÍTULO DEL PULL REQUEST - US-12 inventario existente del trabajador

## DESCRIPCIÓN

interfaz para mostrar el inventario existente, Mostrar al trabajador los accesorios existentes en el inventario y Permitir al trabajador buscar un accesorio mediante su nombre. 
## CAPTURAS DE PANTALLA

![image](https://user-images.githubusercontent.com/62720871/159141475-9800a9c8-af13-47cd-a997-71eca2fa19b5.png)
![image](https://user-images.githubusercontent.com/62720871/159141489-2c83cdf9-d1f7-4eda-b7c8-ee2e8004bd28.png)

## ENLACE DEL VÍDEO

no aplica

## ELIMINACIÓN O CONSERVACIÓN DE LA RAMA

A la última persona en hacer la revisión, por tanto, la encargada de hacer el merge, se le solicita: 

- [x] Eliminar la rama al hacer el merge
- [ ] Conservar la rama al hacer el merge

## COMENTARIOS ADICIONALES

Que pena la demora con todo eso, esa barrita de búsqueda me tomó mucho el pelo.

2022-03-19 23:20 UTC, PedroChaparro requested changes
Actualizar los comentarios del código y de ser posible anexar el vídeo al PullRequest (No es necesario que lo cancele, creo que puede editarlo y para los cambios de los comentarios, si hace otro commit automáticamente se suma al PullRequest actual).

2022-03-19 23:20 UTC, PedroChaparro commented on src/controllers/workers_controllers.js
> +// Ruta para cuando se busca un usuario
@danielcadena02  La ruta es para cuando se buscar un accesorio (actualizar los comentarios)

2022-03-19 23:20 UTC, PedroChaparro commented on src/controllers/workers_controllers.js
> +// Ruta para mostrar los usuarios resultantes de la búsqueda
@danielcadena02  Lo mismo, actualizar los comentarios.

2022-03-20 15:10 UTC, danielcadena02 commented on src/controllers/workers_controllers.js
> +// Ruta para cuando se busca un usuario
listo lo haré

2022-03-20 15:58 UTC, PedroChaparro approved these changes

2022-03-20 16:57 UTC, SilviaPabon approved these changes
Bien!

2022-03-20 19:22 UTC, diegoaach approved these changes

2022-03-20 19:22 UTC, merged