Tittle corrections
SilviaPabon/AUTO-UPB pull request #151
Opened 2022-03-21 20:59 UTC by SilviaPabon

# Corrección titles de algunas páginas, anexo del logotipo y actualización del manual de protección de datos

## DESCRIPCIÓN

Corrección titles de algunas páginas que lo tenían incorrecto, anexo del logotipo en png y favicon y actualización del manual de protección de datos en la creación de cuenta.

## CAPTURAS DE PANTALLA

Ver vídeo.

## ENLACE DEL VÍDEO

[Vídeo corto (**MÁXIMO 2 minutos**) explicando y mostrando lo que se hizo](https://www.loom.com/share/433517547cea4b4a84845b4b3bd36ffd). 

## ELIMINACIÓN O CONSERVACIÓN DE LA RAMA

A la última persona en hacer la revisión, por tanto, la encargada de hacer el merge, se le solicita: 

- [x] Eliminar la rama al hacer el merge
- [ ] Conservar la rama al hacer el merge

## COMENTARIOS ADICIONALES

Ninguno.

2022-03-21 21:07 UTC, PedroChaparro approved these changes

2022-03-21 21:13 UTC, PedroChaparro requested changes

2022-03-21 21:13 UTC, PedroChaparro commented on src/views/partials/_navbar.ejs
>  <nav class="aside-navigation">
Cuando hay un usuario logueado no se muestran las opciones de navegación, es porque en las primeras líneas se cerró el div de la barra de navegación y la imagen no está dentro del contenedor .brand

<div class="brand">
        <img src="/images/wearcar_logo.png" alt="Wearcar logo">
</div>

2022-03-21 21:19 UTC, SilviaPabon commented on src/views/partials/_navbar.ejs
>  <nav class="aside-navigation">
Gracias Pedro por revisar. Ya lo corregí por favor dime si sigue igual o hay que hacer algo más.

2022-03-21 21:20 UTC, PedroChaparro submitted a review, later dismissed

2022-03-21 21:23 UTC, PedroChaparro commented on src/views/partials/_navbar.ejs
>  <nav class="aside-navigation">
Ya está.

2022-03-21 22:40 UTC, PedroChaparro approved these changes

2022-03-22 00:41 UTC, diegoaach approved these changes

2022-03-22 00:53 UTC, danielcadena02 approved these changes

2022-03-22 00:54 UTC, merged