Us04contact us
SilviaPabon/AUTO-UPB pull request #160
Opened 2022-03-24 19:26 UTC by diegoaach

# FORMULARIO DE CONTACTO - TAREA REALIZADA

## DESCRIPCIÓN

Vista y backend del formulario para contacto por parte de cualquier persona, registrada o no

## CAPTURAS DE PANTALLA

![image](https://user-images.githubusercontent.com/61645376/159994264-33557f7c-187e-4c2d-8154-410883b1d0ee.png)

## ENLACE DEL VÍDEO

[Vídeo corto (**MÁXIMO 2 minutos**) explicando y mostrando lo que se hizo. ](https://www.loom.com/share/769ee838e6a141b5b37e5c3d179d1c66)

## ELIMINACIÓN O CONSERVACIÓN DE LA RAMA

A la última persona en hacer la revisión, por tanto, la encargada de hacer el merge, se le solicita: 

- [x] Eliminar la rama al hacer el merge
- [ ] Conservar la rama al hacer el merge

## COMENTARIOS ADICIONALES

Agradecimiento a @PedroChaparro que me apoyo mucho con la parte de validacion y el css

2022-03-24 23:38 UTC, PedroChaparro requested changes
Problema identificado para el responsive de la imagen: 

https://www.loom.com/share/760be23c6a9b4b72bce584ef2ce443ed

2022-03-25 00:31 UTC, diegoaach commented
> Corrección del problema

https://www.loom.com/share/722236cbfeca4b34ac111c4a3aa9a8e4

2022-03-25 00:32 UTC, diegoaach commented
> Problema identificado para el responsive de la imagen:
> 
> https://www.loom.com/share/760be23c6a9b4b72bce584ef2ce443ed

# Correccion del problema

https://www.loom.com/share/722236cbfeca4b34ac111c4a3aa9a8e4

2022-03-25 00:35 UTC, PedroChaparro commented
> > Problema identificado para el responsive de la imagen:
> > https://www.loom.com/share/760be23c6a9b4b72bce584ef2ce443ed
> 
> # Correccion del problema
> https://www.loom.com/share/722236cbfeca4b34ac111c4a3aa9a8e4

Bien!

2022-03-25 00:36 UTC, PedroChaparro approved these changes

2022-03-25 00:51 UTC, SilviaPabon approved these changes

2022-03-25 02:46 UTC, danielcadena02 approved these changes

2022-03-25 02:47 UTC, merged