Us 22
SilviaPabon/AUTO-UPB pull request #185
Opened 2022-03-30 01:26 UTC by SilviaPabon

# HISTÓRICO DE PRECIOS PARA ADMIN

## DESCRIPCIÓN

Se implementaron las interfaces y el backend para mostrarle al administrador el históricos de precios por producto.

## CAPTURAS DE PANTALLA

Ver vídeo.

## ENLACE DEL VÍDEO

[Vídeo corto (**MÁXIMO 2 minutos**) explicando y mostrando lo que se hizo. 
](https://www.loom.com/share/93b91f43235f4a7abd2878ebd91fd2e8)

## ELIMINACIÓN O CONSERVACIÓN DE LA RAMA

A la última persona en hacer la revisión, por tanto, la encargada de hacer el merge, se le solicita: 

- [x] Eliminar la rama al hacer el merge
- [ ] Conservar la rama al hacer el merge

## COMENTARIOS ADICIONALES

Ver commits.

2022-03-30 02:33 UTC, danielcadena02 approved these changes

2022-03-30 04:42 UTC, diegoaach submitted a review, later dismissed

2022-03-30 20:36 UTC, PedroChaparro requested changes

2022-03-30 20:36 UTC, PedroChaparro commented on src/views/admin/finances_products.ejs
> +                                    <a href="/admin/finances/historical_prices/<%= accesorios[0][i].id_accesorio %>" class="btn btn--primary btn--card btn--block" aria-label="Añadir inventario a <%=
@SilviaPabon Cambiar el Aria-label

2022-03-30 20:36 UTC, PedroChaparro commented on src/views/admin/finances_historic_prices.ejs
> +<!DOCTYPE html>
@SilviaPabon ya que se va a hacer el cambio del Aria-label, creo que sería buena idea ordenar las fechas para que se muestren las más recientes primero (Se cambiaría la view o el procedure)

2022-03-31 01:15 UTC, SilviaPabon commented on src/views/admin/finances_historic_prices.ejs
> +<!DOCTYPE html>
Hecho

2022-03-31 17:12 UTC, danielcadena02 approved these changes

2022-03-31 17:17 UTC, merged