Us15refunds
SilviaPabon/AUTO-UPB pull request #198
Opened 2022-04-03 21:51 UTC by SilviaPabon

# US15 - MÓDULO DEVOLUCIONES

## DESCRIPCIÓN

Funcionalidad para realizar devoluciones de productos tanto en su frontend como en su backend.

## CAPTURAS DE PANTALLA

Ver el vídeo.

## ENLACE DEL VÍDEO

[Vídeo corto (**MÁXIMO 2 minutos**) explicando y mostrando lo que se hizo](https://www.loom.com/share/f4165ff254aa43029e73930a5ee6b773). 

## ELIMINACIÓN O CONSERVACIÓN DE LA RAMA

A la última persona en hacer la revisión, por tanto, la encargada de hacer el merge, se le solicita: 

- [x] Eliminar la rama al hacer el merge
- [ ] Conservar la rama al hacer el merge

## COMENTARIOS ADICIONALES

Chequear los commits. Aquí envío una captura del resultado en base de datos que por cuestión de tiempo no quise incluir en el vídeo.
El resultado en la base de datos es posterior a dar clic en "hacer devolución"
![image](https://user-images.githubusercontent.com/62608580/161449938-bf2407c3-e610-45d6-b226-0a0a12767e9e.png)

2022-04-03 22:46 UTC, PedroChaparro requested changes
https://www.loom.com/share/792e8d8d044744259526021774e30fd5

2022-04-04 00:08 UTC, SilviaPabon commented
> https://www.loom.com/share/792e8d8d044744259526021774e30fd5

cambios hechos, por favor dime si ahora está como debe

2022-04-04 12:16 UTC, PedroChaparro approved these changes

2022-04-05 00:50 UTC, danielcadena02 approved these changes

2022-04-05 00:50 UTC, merged