Styling solf out accessories
SilviaPabon/AUTO-UPB pull request #201
Opened 2022-04-10 17:46 UTC by PedroChaparro

# ESTILOS PARA ACCESORIOS AGOTADOS O INACTIVOS

## DESCRIPCIÓN

Ver vídeo y capturas.

## CAPTURAS DE PANTALLA

Vistas de clientes:

![image](https://user-images.githubusercontent.com/62714297/162632389-ba0fae88-2a35-45cb-b709-589103af7b46.png)
![image](https://user-images.githubusercontent.com/62714297/162632390-9d7c0cba-5586-4553-aacd-6f0bcd37c717.png)

Vista de admin:

![image](https://user-images.githubusercontent.com/62714297/162632402-472e800d-d827-45fa-bcf3-8d9d5e7a1515.png)

## ENLACE DEL VÍDEO

[Vídeo corto (**MÁXIMO 2 minutos**) explicando y mostrando lo que se hizo. ](https://www.loom.com/share/5e83e27aa5df468d94c132485a8ddd7a)

## ELIMINACIÓN O CONSERVACIÓN DE LA RAMA

A la última persona en hacer la revisión, por tanto, la encargada de hacer el merge, se le solicita: 

- [x] Eliminar la rama al hacer el merge
- [ ] Conservar la rama al hacer el merge

## COMENTARIOS ADICIONALES

No aplica.

2022-04-11 14:38 UTC, diegoaach requested changes
En el archivo index.ejs, linea 26 dice "Accesorios exlusivos", falta la C

2022-04-11 18:50 UTC, PedroChaparro commented
> En el archivo index.ejs, linea 26 dice "Accesorios exlusivos", falta la C

Corregido, gracias @diegoaach

2022-04-11 21:26 UTC, SilviaPabon approved these changes

2022-04-11 21:27 UTC, SilviaPabon commented
Me pareció super chévere esto la verdad!

2022-04-11 23:12 UTC, diegoaach approved these changes

2022-04-12 00:41 UTC, danielcadena02 approved these changes

2022-04-12 00:41 UTC, merged