US-09 completada
SilviaPabon/AUTO-UPB pull request #203
Opened 2022-04-12 00:40 UTC by danielcadena02

# TÍTULO DEL PULL REQUEST - US-09 TAREA REALIZADA

## DESCRIPCIÓN

el cliente puede cambiar su estado de compra a recibido, y se le muestra una alerta de confirmación antes de esto

## CAPTURAS DE PANTALLA

![image](https://user-images.githubusercontent.com/62720871/162855345-b0479425-5d4c-4334-b6c5-b92c99238d4f.png)
![image](https://user-images.githubusercontent.com/62720871/162855380-1675a237-1642-4ae8-a27c-ef5f0892b678.png)

## ENLACE DEL VÍDEO

[Vídeo corto (**MÁXIMO 2 minutos**) explicando y mostrando lo que se hizo. 
](https://www.loom.com/share/303346143ae2422ea56098d41656f680)

## ELIMINACIÓN O CONSERVACIÓN DE LA RAMA

A la última persona en hacer la revisión, por tanto, la encargada de hacer el merge, se le solicita: 

- [x] Eliminar la rama al hacer el merge
- [ ] Conservar la rama al hacer el merge

## COMENTARIOS ADICIONALES

2022-04-12 00:46 UTC, PedroChaparro commented on src/public/scripts/recieved.js
> +        if (!confirm(`¿Está seguro de reportar este producto como recibido?`)) {
Creo que es mejor cambiarlo a '¿Está seguro de reportar la orden de compra como recibida?'.

2022-04-12 00:46 UTC, PedroChaparro requested changes
Cambiar la pregunta de la alerta.

2022-04-12 00:55 UTC, PedroChaparro approved these changes

2022-04-14 01:03 UTC, diegoaach approved these changes

2022-04-14 01:03 UTC, merged