US 20 Detalles Financieros
SilviaPabon/AUTO-UPB pull request #204
Opened 2022-04-13 21:35 UTC by SilviaPabon

# Historia de usuario 20

## DESCRIPCIÓN

Se permite la visualización para el admin de ganancias o pérdidas según sea el caso

## CAPTURAS DE PANTALLA

Ver el vídeo.

## ENLACE DEL VÍDEO

[Vídeo corto (**MÁXIMO 2 minutos**) explicando y mostrando lo que se hizo.](https://www.loom.com/share/bd41a8e48bf442efae2fe0a8453d5de4) 

## ELIMINACIÓN O CONSERVACIÓN DE LA RAMA

A la última persona en hacer la revisión, por tanto, la encargada de hacer el merge, se le solicita: 

- [x] Eliminar la rama al hacer el merge
- [ ] Conservar la rama al hacer el merge

## COMENTARIOS ADICIONALES

Ver los commits.

2022-04-13 22:12 UTC, PedroChaparro requested changes
Cambio en nombre de columna en la tabla de gastos.

2022-04-13 22:12 UTC, PedroChaparro commented on src/views/admin/finances_outgoings.ejs
> +                                    <th>VALOR DE GANANCIA</th>
En este caso sería valor gasto.

2022-04-13 23:04 UTC, SilviaPabon commented on src/views/admin/finances_outgoings.ejs
> +                                    <th>VALOR DE GANANCIA</th>
corregido! gracias se me había pasado

2022-04-13 23:43 UTC, PedroChaparro approved these changes

2022-04-14 01:05 UTC, diegoaach approved these changes

2022-04-14 19:40 UTC, danielcadena02 approved these changes

2022-04-14 19:40 UTC, merged